# Generated by Django 5.1.3 on 2026-03-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tally_ledger_name', models.CharField(help_text='Exact ledger name as it appears in Tally XML', max_length=255, unique=True)),
                ('report_section', models.CharField(help_text="e.g., 'Assets', 'Equity & Liabilities', 'Income', 'Expenses'", max_length=100)),
                ('report_group', models.CharField(help_text="e.g., 'Loans (Liability)', 'Indirect Expenses'", max_length=150)),
                ('line_item', models.CharField(help_text="e.g., 'Salary A/c', 'Other Loans'", max_length=150)),
                ('cost_center', models.CharField(blank=True, help_text="Optional. The logical cost center group for Matrix reporting (e.g., 'BTM 12th Main')", max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['report_section', 'report_group', 'tally_ledger_name'],
            },
        ),
    ]
