# Generated by Django 5.1.3 on 2026-04-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_engine', '0004_seed_costcenters'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='costcenter',
            name='unique_cc_per_building',
        ),
        migrations.AddField(
            model_name='costcenter',
            name='rent_weight',
            field=models.FloatField(default=1.0, help_text='Relative rent share weight within the building. Default 1.0 = equal split. E.g. set 2.2 for a unit that pays 55k when others pay 25k.'),
        ),
        migrations.AlterUniqueTogether(
            name='costcenter',
            unique_together={('building', 'display_name')},
        ),
    ]
